// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thegame.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PLAYER_STATE int32

const (
	PLAYER_STATE_UNKNOWN      PLAYER_STATE = 0
	PLAYER_STATE_JOINED       PLAYER_STATE = 1
	PLAYER_STATE_PLAYING      PLAYER_STATE = 2
	PLAYER_STATE_DISCONNECTED PLAYER_STATE = 3
)

var PLAYER_STATE_name = map[int32]string{
	0: "UNKNOWN",
	1: "JOINED",
	2: "PLAYING",
	3: "DISCONNECTED",
}

var PLAYER_STATE_value = map[string]int32{
	"UNKNOWN":      0,
	"JOINED":       1,
	"PLAYING":      2,
	"DISCONNECTED": 3,
}

func (x PLAYER_STATE) String() string {
	return proto.EnumName(PLAYER_STATE_name, int32(x))
}

func (PLAYER_STATE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0032e2c8eecaa438, []int{0}
}

type Room struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_0032e2c8eecaa438, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateRoomReq struct {
	StartingPlayer       *Player  `protobuf:"bytes,1,opt,name=starting_player,json=startingPlayer,proto3" json:"starting_player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomReq) Reset()         { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()    {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0032e2c8eecaa438, []int{1}
}

func (m *CreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomReq.Unmarshal(m, b)
}
func (m *CreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomReq.Marshal(b, m, deterministic)
}
func (m *CreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomReq.Merge(m, src)
}
func (m *CreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoomReq.Size(m)
}
func (m *CreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomReq proto.InternalMessageInfo

func (m *CreateRoomReq) GetStartingPlayer() *Player {
	if m != nil {
		return m.StartingPlayer
	}
	return nil
}

type RoomState struct {
	Room                 *Room     `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Players              []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	CurrentRound         *Round    `protobuf:"bytes,3,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`
	Rounds               []*Round  `protobuf:"bytes,4,rep,name=rounds,proto3" json:"rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoomState) Reset()         { *m = RoomState{} }
func (m *RoomState) String() string { return proto.CompactTextString(m) }
func (*RoomState) ProtoMessage()    {}
func (*RoomState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0032e2c8eecaa438, []int{2}
}

func (m *RoomState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomState.Unmarshal(m, b)
}
func (m *RoomState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomState.Marshal(b, m, deterministic)
}
func (m *RoomState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomState.Merge(m, src)
}
func (m *RoomState) XXX_Size() int {
	return xxx_messageInfo_RoomState.Size(m)
}
func (m *RoomState) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomState.DiscardUnknown(m)
}

var xxx_messageInfo_RoomState proto.InternalMessageInfo

func (m *RoomState) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *RoomState) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomState) GetCurrentRound() *Round {
	if m != nil {
		return m.CurrentRound
	}
	return nil
}

func (m *RoomState) GetRounds() []*Round {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type Round struct {
	Number               uint64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Winner               *Player   `protobuf:"bytes,2,opt,name=winner,proto3" json:"winner,omitempty"`
	Players              []*Player `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Round) Reset()         { *m = Round{} }
func (m *Round) String() string { return proto.CompactTextString(m) }
func (*Round) ProtoMessage()    {}
func (*Round) Descriptor() ([]byte, []int) {
	return fileDescriptor_0032e2c8eecaa438, []int{3}
}

func (m *Round) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Round.Unmarshal(m, b)
}
func (m *Round) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Round.Marshal(b, m, deterministic)
}
func (m *Round) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Round.Merge(m, src)
}
func (m *Round) XXX_Size() int {
	return xxx_messageInfo_Round.Size(m)
}
func (m *Round) XXX_DiscardUnknown() {
	xxx_messageInfo_Round.DiscardUnknown(m)
}

var xxx_messageInfo_Round proto.InternalMessageInfo

func (m *Round) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Round) GetWinner() *Player {
	if m != nil {
		return m.Winner
	}
	return nil
}

func (m *Round) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Player struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State                PLAYER_STATE `protobuf:"varint,3,opt,name=state,proto3,enum=protobuf.PLAYER_STATE" json:"state,omitempty"`
	Score                int64        `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_0032e2c8eecaa438, []int{4}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetState() PLAYER_STATE {
	if m != nil {
		return m.State
	}
	return PLAYER_STATE_UNKNOWN
}

func (m *Player) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuf.PLAYER_STATE", PLAYER_STATE_name, PLAYER_STATE_value)
	proto.RegisterType((*Room)(nil), "protobuf.Room")
	proto.RegisterType((*CreateRoomReq)(nil), "protobuf.CreateRoomReq")
	proto.RegisterType((*RoomState)(nil), "protobuf.RoomState")
	proto.RegisterType((*Round)(nil), "protobuf.Round")
	proto.RegisterType((*Player)(nil), "protobuf.Player")
}

func init() { proto.RegisterFile("thegame.proto", fileDescriptor_0032e2c8eecaa438) }

var fileDescriptor_0032e2c8eecaa438 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4f, 0x8f, 0xd2, 0x40,
	0x14, 0xb7, 0x7f, 0xe8, 0xc2, 0x83, 0x76, 0x9b, 0xa7, 0xc1, 0xc6, 0x13, 0xe9, 0x45, 0xb2, 0x31,
	0x68, 0x58, 0x2f, 0x26, 0x5e, 0x76, 0xa1, 0x12, 0xd0, 0x14, 0x33, 0x60, 0x8c, 0x5e, 0x48, 0xa1,
	0x23, 0x36, 0xb1, 0x33, 0x38, 0x9d, 0xc6, 0x78, 0xf0, 0x8b, 0xf9, 0xe9, 0x4c, 0xa7, 0x6d, 0x28,
	0x22, 0xf1, 0xd4, 0x79, 0xf3, 0xfb, 0x37, 0xef, 0xf5, 0x81, 0x2d, 0xbf, 0xd2, 0x7d, 0x94, 0xd2,
	0xd1, 0x41, 0x70, 0xc9, 0xb1, 0xad, 0x3e, 0xdb, 0xfc, 0x8b, 0xdf, 0x07, 0x93, 0x70, 0x9e, 0xa2,
	0x03, 0x7a, 0x12, 0x7b, 0xda, 0x40, 0x1b, 0x76, 0x88, 0x9e, 0xc4, 0xfe, 0x02, 0xec, 0x89, 0xa0,
	0x91, 0xa4, 0x05, 0x4a, 0xe8, 0x77, 0x7c, 0x05, 0xd7, 0x99, 0x8c, 0x84, 0x4c, 0xd8, 0x7e, 0x73,
	0xf8, 0x16, 0xfd, 0xa4, 0x42, 0xb1, 0xbb, 0x63, 0x77, 0x54, 0x9b, 0x8d, 0xde, 0xab, 0x7b, 0xe2,
	0xd4, 0xc4, 0xb2, 0xf6, 0x7f, 0x6b, 0xd0, 0x29, 0x6c, 0x56, 0x32, 0x92, 0x14, 0x7d, 0x30, 0x05,
	0xe7, 0x69, 0xa5, 0x76, 0x8e, 0x6a, 0x95, 0xa4, 0x30, 0xbc, 0x81, 0xab, 0x32, 0x23, 0xf3, 0xf4,
	0x81, 0xf1, 0xcf, 0x90, 0x9a, 0x80, 0x2f, 0xc1, 0xde, 0xe5, 0x42, 0x50, 0x26, 0x37, 0x82, 0xe7,
	0x2c, 0xf6, 0x0c, 0x65, 0x7c, 0xdd, 0x34, 0xce, 0x59, 0x4c, 0x7a, 0x15, 0x4b, 0x55, 0xf8, 0x14,
	0x2c, 0xc5, 0xce, 0x3c, 0x53, 0x05, 0x9c, 0xd1, 0x2b, 0xd8, 0xcf, 0xa1, 0x55, 0x2a, 0xfa, 0x60,
	0xb1, 0x3c, 0xdd, 0x56, 0x7d, 0x9b, 0xa4, 0xaa, 0x70, 0x08, 0xd6, 0x8f, 0x84, 0x31, 0x2a, 0x3c,
	0xfd, 0xc2, 0x3c, 0x2a, 0xbc, 0xd9, 0x95, 0xf1, 0x9f, 0xae, 0xfc, 0x03, 0x58, 0xe5, 0xd5, 0xdf,
	0x7f, 0x06, 0x11, 0x4c, 0x16, 0xa5, 0x54, 0xa5, 0x75, 0x88, 0x3a, 0xe3, 0x33, 0x68, 0x65, 0xc5,
	0x70, 0x55, 0xef, 0xce, 0xb8, 0xdf, 0xf0, 0x7d, 0x77, 0xf7, 0x29, 0x20, 0x9b, 0xd5, 0xfa, 0x6e,
	0x1d, 0x90, 0x92, 0x84, 0x8f, 0xa0, 0x95, 0xed, 0xb8, 0xa0, 0x9e, 0x39, 0xd0, 0x86, 0x06, 0x29,
	0x8b, 0x9b, 0x37, 0xd0, 0x6b, 0x92, 0xb1, 0x0b, 0x57, 0x1f, 0xc2, 0xb7, 0xe1, 0xf2, 0x63, 0xe8,
	0x3e, 0x40, 0x00, 0x6b, 0xb1, 0x9c, 0x87, 0xc1, 0xd4, 0xd5, 0x0a, 0xa0, 0x20, 0xce, 0xc3, 0x99,
	0xab, 0xa3, 0x0b, 0xbd, 0xe9, 0x7c, 0x35, 0x59, 0x86, 0x61, 0x30, 0x59, 0x07, 0x53, 0xd7, 0x18,
	0xff, 0x82, 0xf6, 0x7d, 0x94, 0xd1, 0x59, 0xf1, 0xae, 0xd7, 0x00, 0xc7, 0x2d, 0xc2, 0xc7, 0xc7,
	0x67, 0x9d, 0xec, 0xd6, 0x93, 0x87, 0xa7, 0x4b, 0xa0, 0xf6, 0xe4, 0x85, 0x86, 0xb7, 0xd0, 0x5e,
	0xf0, 0x84, 0x29, 0xed, 0xd9, 0xa8, 0x2e, 0x88, 0xee, 0xed, 0xcf, 0xdd, 0x3d, 0x7f, 0x5e, 0x43,
	0x5b, 0x4b, 0x9d, 0x6e, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x61, 0xb7, 0x42, 0xd9, 0x01, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BaseGameClient is the client API for BaseGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BaseGameClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (BaseGame_CreateRoomClient, error)
	JoinRoom(ctx context.Context, in *Player, opts ...grpc.CallOption) (BaseGame_JoinRoomClient, error)
}

type baseGameClient struct {
	cc *grpc.ClientConn
}

func NewBaseGameClient(cc *grpc.ClientConn) BaseGameClient {
	return &baseGameClient{cc}
}

func (c *baseGameClient) CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (BaseGame_CreateRoomClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BaseGame_serviceDesc.Streams[0], "/protobuf.BaseGame/CreateRoom", opts...)
	if err != nil {
		return nil, err
	}
	x := &baseGameCreateRoomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BaseGame_CreateRoomClient interface {
	Recv() (*RoomState, error)
	grpc.ClientStream
}

type baseGameCreateRoomClient struct {
	grpc.ClientStream
}

func (x *baseGameCreateRoomClient) Recv() (*RoomState, error) {
	m := new(RoomState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *baseGameClient) JoinRoom(ctx context.Context, in *Player, opts ...grpc.CallOption) (BaseGame_JoinRoomClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BaseGame_serviceDesc.Streams[1], "/protobuf.BaseGame/JoinRoom", opts...)
	if err != nil {
		return nil, err
	}
	x := &baseGameJoinRoomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BaseGame_JoinRoomClient interface {
	Recv() (*RoomState, error)
	grpc.ClientStream
}

type baseGameJoinRoomClient struct {
	grpc.ClientStream
}

func (x *baseGameJoinRoomClient) Recv() (*RoomState, error) {
	m := new(RoomState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BaseGameServer is the server API for BaseGame service.
type BaseGameServer interface {
	CreateRoom(*CreateRoomReq, BaseGame_CreateRoomServer) error
	JoinRoom(*Player, BaseGame_JoinRoomServer) error
}

func RegisterBaseGameServer(s *grpc.Server, srv BaseGameServer) {
	s.RegisterService(&_BaseGame_serviceDesc, srv)
}

func _BaseGame_CreateRoom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateRoomReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseGameServer).CreateRoom(m, &baseGameCreateRoomServer{stream})
}

type BaseGame_CreateRoomServer interface {
	Send(*RoomState) error
	grpc.ServerStream
}

type baseGameCreateRoomServer struct {
	grpc.ServerStream
}

func (x *baseGameCreateRoomServer) Send(m *RoomState) error {
	return x.ServerStream.SendMsg(m)
}

func _BaseGame_JoinRoom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Player)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BaseGameServer).JoinRoom(m, &baseGameJoinRoomServer{stream})
}

type BaseGame_JoinRoomServer interface {
	Send(*RoomState) error
	grpc.ServerStream
}

type baseGameJoinRoomServer struct {
	grpc.ServerStream
}

func (x *baseGameJoinRoomServer) Send(m *RoomState) error {
	return x.ServerStream.SendMsg(m)
}

var _BaseGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.BaseGame",
	HandlerType: (*BaseGameServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateRoom",
			Handler:       _BaseGame_CreateRoom_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "JoinRoom",
			Handler:       _BaseGame_JoinRoom_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "thegame.proto",
}
