// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stm/shoot_the_messenger.proto

package stm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prompt struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Contents             string   `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prompt) Reset()         { *m = Prompt{} }
func (m *Prompt) String() string { return proto.CompactTextString(m) }
func (*Prompt) ProtoMessage()    {}
func (*Prompt) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{0}
}

func (m *Prompt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prompt.Unmarshal(m, b)
}
func (m *Prompt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prompt.Marshal(b, m, deterministic)
}
func (m *Prompt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prompt.Merge(m, src)
}
func (m *Prompt) XXX_Size() int {
	return xxx_messageInfo_Prompt.Size(m)
}
func (m *Prompt) XXX_DiscardUnknown() {
	xxx_messageInfo_Prompt.DiscardUnknown(m)
}

var xxx_messageInfo_Prompt proto.InternalMessageInfo

func (m *Prompt) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Prompt) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

type RoleFrame struct {
	Guesser              bool     `protobuf:"varint,1,opt,name=guesser,proto3" json:"guesser,omitempty"`
	Out                  bool     `protobuf:"varint,2,opt,name=out,proto3" json:"out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleFrame) Reset()         { *m = RoleFrame{} }
func (m *RoleFrame) String() string { return proto.CompactTextString(m) }
func (*RoleFrame) ProtoMessage()    {}
func (*RoleFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{1}
}

func (m *RoleFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleFrame.Unmarshal(m, b)
}
func (m *RoleFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleFrame.Marshal(b, m, deterministic)
}
func (m *RoleFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleFrame.Merge(m, src)
}
func (m *RoleFrame) XXX_Size() int {
	return xxx_messageInfo_RoleFrame.Size(m)
}
func (m *RoleFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleFrame.DiscardUnknown(m)
}

var xxx_messageInfo_RoleFrame proto.InternalMessageInfo

func (m *RoleFrame) GetGuesser() bool {
	if m != nil {
		return m.Guesser
	}
	return false
}

func (m *RoleFrame) GetOut() bool {
	if m != nil {
		return m.Out
	}
	return false
}

type GuessFrame struct {
	PromptId             string   `protobuf:"bytes,1,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	ResponseId           string   `protobuf:"bytes,2,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuessFrame) Reset()         { *m = GuessFrame{} }
func (m *GuessFrame) String() string { return proto.CompactTextString(m) }
func (*GuessFrame) ProtoMessage()    {}
func (*GuessFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{2}
}

func (m *GuessFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuessFrame.Unmarshal(m, b)
}
func (m *GuessFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuessFrame.Marshal(b, m, deterministic)
}
func (m *GuessFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuessFrame.Merge(m, src)
}
func (m *GuessFrame) XXX_Size() int {
	return xxx_messageInfo_GuessFrame.Size(m)
}
func (m *GuessFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_GuessFrame.DiscardUnknown(m)
}

var xxx_messageInfo_GuessFrame proto.InternalMessageInfo

func (m *GuessFrame) GetPromptId() string {
	if m != nil {
		return m.PromptId
	}
	return ""
}

func (m *GuessFrame) GetResponseId() string {
	if m != nil {
		return m.ResponseId
	}
	return ""
}

type PromptResponseFrame struct {
	PromptId             string   `protobuf:"bytes,1,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	Response             string   `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromptResponseFrame) Reset()         { *m = PromptResponseFrame{} }
func (m *PromptResponseFrame) String() string { return proto.CompactTextString(m) }
func (*PromptResponseFrame) ProtoMessage()    {}
func (*PromptResponseFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{3}
}

func (m *PromptResponseFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptResponseFrame.Unmarshal(m, b)
}
func (m *PromptResponseFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptResponseFrame.Marshal(b, m, deterministic)
}
func (m *PromptResponseFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptResponseFrame.Merge(m, src)
}
func (m *PromptResponseFrame) XXX_Size() int {
	return xxx_messageInfo_PromptResponseFrame.Size(m)
}
func (m *PromptResponseFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptResponseFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PromptResponseFrame proto.InternalMessageInfo

func (m *PromptResponseFrame) GetPromptId() string {
	if m != nil {
		return m.PromptId
	}
	return ""
}

func (m *PromptResponseFrame) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type PromptResponseInputFrame struct {
	PromptId             string   `protobuf:"bytes,1,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PromptResponseInputFrame) Reset()         { *m = PromptResponseInputFrame{} }
func (m *PromptResponseInputFrame) String() string { return proto.CompactTextString(m) }
func (*PromptResponseInputFrame) ProtoMessage()    {}
func (*PromptResponseInputFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{4}
}

func (m *PromptResponseInputFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromptResponseInputFrame.Unmarshal(m, b)
}
func (m *PromptResponseInputFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromptResponseInputFrame.Marshal(b, m, deterministic)
}
func (m *PromptResponseInputFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromptResponseInputFrame.Merge(m, src)
}
func (m *PromptResponseInputFrame) XXX_Size() int {
	return xxx_messageInfo_PromptResponseInputFrame.Size(m)
}
func (m *PromptResponseInputFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PromptResponseInputFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PromptResponseInputFrame proto.InternalMessageInfo

func (m *PromptResponseInputFrame) GetPromptId() string {
	if m != nil {
		return m.PromptId
	}
	return ""
}

type PlayerFrame struct {
	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	// Types that are valid to be assigned to Frame:
	//	*PlayerFrame_Started
	//	*PlayerFrame_Guess
	//	*PlayerFrame_PromptResponseInput
	//	*PlayerFrame_PromptResponse
	//	*PlayerFrame_RoleChange
	Frame                isPlayerFrame_Frame `protobuf_oneof:"frame"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PlayerFrame) Reset()         { *m = PlayerFrame{} }
func (m *PlayerFrame) String() string { return proto.CompactTextString(m) }
func (*PlayerFrame) ProtoMessage()    {}
func (*PlayerFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{5}
}

func (m *PlayerFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerFrame.Unmarshal(m, b)
}
func (m *PlayerFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerFrame.Marshal(b, m, deterministic)
}
func (m *PlayerFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerFrame.Merge(m, src)
}
func (m *PlayerFrame) XXX_Size() int {
	return xxx_messageInfo_PlayerFrame.Size(m)
}
func (m *PlayerFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerFrame.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerFrame proto.InternalMessageInfo

func (m *PlayerFrame) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

type isPlayerFrame_Frame interface {
	isPlayerFrame_Frame()
}

type PlayerFrame_Started struct {
	Started *GameStarted `protobuf:"bytes,2,opt,name=started,proto3,oneof"`
}

type PlayerFrame_Guess struct {
	Guess *GuessFrame `protobuf:"bytes,3,opt,name=guess,proto3,oneof"`
}

type PlayerFrame_PromptResponseInput struct {
	PromptResponseInput *PromptResponseInputFrame `protobuf:"bytes,4,opt,name=prompt_response_input,json=promptResponseInput,proto3,oneof"`
}

type PlayerFrame_PromptResponse struct {
	PromptResponse *PromptResponseFrame `protobuf:"bytes,5,opt,name=prompt_response,json=promptResponse,proto3,oneof"`
}

type PlayerFrame_RoleChange struct {
	RoleChange *RoleFrame `protobuf:"bytes,6,opt,name=role_change,json=roleChange,proto3,oneof"`
}

func (*PlayerFrame_Started) isPlayerFrame_Frame() {}

func (*PlayerFrame_Guess) isPlayerFrame_Frame() {}

func (*PlayerFrame_PromptResponseInput) isPlayerFrame_Frame() {}

func (*PlayerFrame_PromptResponse) isPlayerFrame_Frame() {}

func (*PlayerFrame_RoleChange) isPlayerFrame_Frame() {}

func (m *PlayerFrame) GetFrame() isPlayerFrame_Frame {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (m *PlayerFrame) GetStarted() *GameStarted {
	if x, ok := m.GetFrame().(*PlayerFrame_Started); ok {
		return x.Started
	}
	return nil
}

func (m *PlayerFrame) GetGuess() *GuessFrame {
	if x, ok := m.GetFrame().(*PlayerFrame_Guess); ok {
		return x.Guess
	}
	return nil
}

func (m *PlayerFrame) GetPromptResponseInput() *PromptResponseInputFrame {
	if x, ok := m.GetFrame().(*PlayerFrame_PromptResponseInput); ok {
		return x.PromptResponseInput
	}
	return nil
}

func (m *PlayerFrame) GetPromptResponse() *PromptResponseFrame {
	if x, ok := m.GetFrame().(*PlayerFrame_PromptResponse); ok {
		return x.PromptResponse
	}
	return nil
}

func (m *PlayerFrame) GetRoleChange() *RoleFrame {
	if x, ok := m.GetFrame().(*PlayerFrame_RoleChange); ok {
		return x.RoleChange
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PlayerFrame) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PlayerFrame_Started)(nil),
		(*PlayerFrame_Guess)(nil),
		(*PlayerFrame_PromptResponseInput)(nil),
		(*PlayerFrame_PromptResponse)(nil),
		(*PlayerFrame_RoleChange)(nil),
	}
}

type BeginGameReq struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginGameReq) Reset()         { *m = BeginGameReq{} }
func (m *BeginGameReq) String() string { return proto.CompactTextString(m) }
func (*BeginGameReq) ProtoMessage()    {}
func (*BeginGameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{6}
}

func (m *BeginGameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginGameReq.Unmarshal(m, b)
}
func (m *BeginGameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginGameReq.Marshal(b, m, deterministic)
}
func (m *BeginGameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginGameReq.Merge(m, src)
}
func (m *BeginGameReq) XXX_Size() int {
	return xxx_messageInfo_BeginGameReq.Size(m)
}
func (m *BeginGameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginGameReq.DiscardUnknown(m)
}

var xxx_messageInfo_BeginGameReq proto.InternalMessageInfo

func (m *BeginGameReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type GameStarted struct {
	Prompts              []*Prompt `protobuf:"bytes,1,rep,name=prompts,proto3" json:"prompts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameStarted) Reset()         { *m = GameStarted{} }
func (m *GameStarted) String() string { return proto.CompactTextString(m) }
func (*GameStarted) ProtoMessage()    {}
func (*GameStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4170d256edd2c8d, []int{7}
}

func (m *GameStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameStarted.Unmarshal(m, b)
}
func (m *GameStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameStarted.Marshal(b, m, deterministic)
}
func (m *GameStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameStarted.Merge(m, src)
}
func (m *GameStarted) XXX_Size() int {
	return xxx_messageInfo_GameStarted.Size(m)
}
func (m *GameStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_GameStarted.DiscardUnknown(m)
}

var xxx_messageInfo_GameStarted proto.InternalMessageInfo

func (m *GameStarted) GetPrompts() []*Prompt {
	if m != nil {
		return m.Prompts
	}
	return nil
}

func init() {
	proto.RegisterType((*Prompt)(nil), "stm.Prompt")
	proto.RegisterType((*RoleFrame)(nil), "stm.RoleFrame")
	proto.RegisterType((*GuessFrame)(nil), "stm.GuessFrame")
	proto.RegisterType((*PromptResponseFrame)(nil), "stm.PromptResponseFrame")
	proto.RegisterType((*PromptResponseInputFrame)(nil), "stm.PromptResponseInputFrame")
	proto.RegisterType((*PlayerFrame)(nil), "stm.PlayerFrame")
	proto.RegisterType((*BeginGameReq)(nil), "stm.BeginGameReq")
	proto.RegisterType((*GameStarted)(nil), "stm.GameStarted")
}

func init() { proto.RegisterFile("stm/shoot_the_messenger.proto", fileDescriptor_a4170d256edd2c8d) }

var fileDescriptor_a4170d256edd2c8d = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xed, 0x07, 0x6d, 0xd2, 0x9b, 0xa9, 0xdb, 0xee, 0x84, 0xb0, 0x8a, 0x26, 0xa6, 0x48, 0x68,
	0x7d, 0x40, 0x65, 0x94, 0x89, 0xbd, 0x6f, 0x12, 0x6b, 0x90, 0x40, 0x93, 0xcb, 0x7b, 0x15, 0x96,
	0x4b, 0x5b, 0xa9, 0x8e, 0x83, 0xed, 0x3e, 0xf0, 0xc0, 0xef, 0xe4, 0xef, 0x20, 0xdb, 0x73, 0x9a,
	0x51, 0x10, 0xbc, 0xe5, 0x9e, 0x7b, 0xee, 0xf1, 0xf1, 0x89, 0x2f, 0x9c, 0x6a, 0x23, 0x5e, 0xeb,
	0x95, 0x94, 0x66, 0x61, 0x56, 0xb4, 0x10, 0xa4, 0x35, 0x95, 0x4b, 0x52, 0x93, 0x4a, 0x49, 0x23,
	0xb1, 0xab, 0x8d, 0x48, 0x2f, 0xa1, 0x7f, 0xa7, 0xa4, 0xa8, 0x0c, 0x0e, 0xa1, 0xb3, 0x2e, 0x58,
	0xfb, 0xac, 0x3d, 0x1e, 0xf0, 0xce, 0xba, 0xc0, 0x11, 0xc4, 0xf7, 0xb2, 0x34, 0x54, 0x1a, 0xcd,
	0x3a, 0x0e, 0xad, 0xeb, 0xf4, 0x0a, 0x06, 0x5c, 0x6e, 0xe8, 0xbd, 0xca, 0x05, 0x21, 0x83, 0x68,
	0xb9, 0xb5, 0xda, 0xca, 0x4d, 0xc7, 0x3c, 0x94, 0x78, 0x04, 0x5d, 0xb9, 0x35, 0x6e, 0x3a, 0xe6,
	0xf6, 0x33, 0xfd, 0x00, 0x70, 0x6b, 0x9b, 0x7e, 0xf2, 0x39, 0x0c, 0x2a, 0x77, 0xf8, 0xa2, 0x3e,
	0x39, 0xf6, 0x40, 0x56, 0xe0, 0x0b, 0x48, 0x14, 0xe9, 0x4a, 0x96, 0x9a, 0x6c, 0xdb, 0x5b, 0x80,
	0x00, 0x65, 0x45, 0xfa, 0x09, 0x4e, 0xbc, 0x75, 0xfe, 0x80, 0xfd, 0x87, 0xe8, 0x08, 0xe2, 0xa0,
	0x10, 0x2e, 0x15, 0xea, 0xf4, 0x0a, 0xd8, 0x63, 0xbd, 0xac, 0xac, 0xb6, 0xe6, 0xdf, 0xa2, 0xe9,
	0xcf, 0x0e, 0x24, 0x77, 0x9b, 0xfc, 0x3b, 0xa9, 0x1d, 0xd9, 0x95, 0x4d, 0xb2, 0x03, 0xb2, 0x02,
	0x5f, 0x41, 0xa4, 0x4d, 0xae, 0x0c, 0xf9, 0x2b, 0x25, 0xd3, 0xa3, 0x89, 0x36, 0x62, 0x72, 0x9b,
	0x0b, 0x9a, 0x7b, 0x7c, 0xd6, 0xe2, 0x81, 0x82, 0xe7, 0xd0, 0x73, 0x61, 0xb2, 0xae, 0xe3, 0x1e,
	0x7a, 0x6e, 0x9d, 0xe0, 0xac, 0xc5, 0x7d, 0x1f, 0xe7, 0xf0, 0xf4, 0xc1, 0xe0, 0x2e, 0x34, 0x6b,
	0x9f, 0x3d, 0x71, 0x83, 0xa7, 0x6e, 0xf0, 0x6f, 0xd7, 0x9b, 0xb5, 0xf8, 0x49, 0xb5, 0xdf, 0xc3,
	0x1b, 0x38, 0xfc, 0x4d, 0x94, 0xf5, 0x9c, 0x1c, 0xfb, 0x83, 0x5c, 0x50, 0x1a, 0x3e, 0x56, 0xc2,
	0x37, 0x90, 0x28, 0xb9, 0xa1, 0xc5, 0xfd, 0x2a, 0x2f, 0x97, 0xc4, 0xfa, 0x4e, 0x60, 0xe8, 0x04,
	0xea, 0x37, 0x34, 0x6b, 0x71, 0xb0, 0xa4, 0x1b, 0xc7, 0xb9, 0x8e, 0xa0, 0xf7, 0xd5, 0xc2, 0xe9,
	0x39, 0x1c, 0x5c, 0xd3, 0x72, 0x5d, 0xda, 0x74, 0x38, 0x7d, 0xc3, 0x67, 0x10, 0x29, 0x29, 0xc5,
	0x2e, 0xd7, 0xbe, 0x2d, 0xb3, 0x22, 0xbd, 0x84, 0xa4, 0x91, 0x20, 0xbe, 0x84, 0xc8, 0xbb, 0xd0,
	0xac, 0x7d, 0xd6, 0x1d, 0x27, 0xd3, 0xa4, 0x69, 0x38, 0xf4, 0xa6, 0x3f, 0xe0, 0x78, 0x6e, 0xd7,
	0xe3, 0xf3, 0x8a, 0x3e, 0x86, 0xe5, 0xc0, 0x0b, 0x18, 0xd4, 0x67, 0xe2, 0xb1, 0x9b, 0x6b, 0x7a,
	0x18, 0xed, 0xfd, 0x2f, 0x7c, 0x07, 0x07, 0xfe, 0xf7, 0xcf, 0x8d, 0xa2, 0x5c, 0xa0, 0x67, 0x34,
	0x5e, 0xc4, 0x68, 0x0f, 0x19, 0xb7, 0x2f, 0xda, 0x5f, 0xfa, 0x6e, 0x0f, 0xdf, 0xfe, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0x00, 0x8f, 0x36, 0x81, 0xa8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShootTheMessengerClient is the client API for ShootTheMessenger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShootTheMessengerClient interface {
	BeginGame(ctx context.Context, in *BeginGameReq, opts ...grpc.CallOption) (*GameStarted, error)
	PlayerStream(ctx context.Context, opts ...grpc.CallOption) (ShootTheMessenger_PlayerStreamClient, error)
}

type shootTheMessengerClient struct {
	cc *grpc.ClientConn
}

func NewShootTheMessengerClient(cc *grpc.ClientConn) ShootTheMessengerClient {
	return &shootTheMessengerClient{cc}
}

func (c *shootTheMessengerClient) BeginGame(ctx context.Context, in *BeginGameReq, opts ...grpc.CallOption) (*GameStarted, error) {
	out := new(GameStarted)
	err := c.cc.Invoke(ctx, "/stm.ShootTheMessenger/BeginGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shootTheMessengerClient) PlayerStream(ctx context.Context, opts ...grpc.CallOption) (ShootTheMessenger_PlayerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ShootTheMessenger_serviceDesc.Streams[0], "/stm.ShootTheMessenger/PlayerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &shootTheMessengerPlayerStreamClient{stream}
	return x, nil
}

type ShootTheMessenger_PlayerStreamClient interface {
	Send(*PlayerFrame) error
	Recv() (*PlayerFrame, error)
	grpc.ClientStream
}

type shootTheMessengerPlayerStreamClient struct {
	grpc.ClientStream
}

func (x *shootTheMessengerPlayerStreamClient) Send(m *PlayerFrame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shootTheMessengerPlayerStreamClient) Recv() (*PlayerFrame, error) {
	m := new(PlayerFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ShootTheMessengerServer is the server API for ShootTheMessenger service.
type ShootTheMessengerServer interface {
	BeginGame(context.Context, *BeginGameReq) (*GameStarted, error)
	PlayerStream(ShootTheMessenger_PlayerStreamServer) error
}

func RegisterShootTheMessengerServer(s *grpc.Server, srv ShootTheMessengerServer) {
	s.RegisterService(&_ShootTheMessenger_serviceDesc, srv)
}

func _ShootTheMessenger_BeginGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginGameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShootTheMessengerServer).BeginGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stm.ShootTheMessenger/BeginGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShootTheMessengerServer).BeginGame(ctx, req.(*BeginGameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShootTheMessenger_PlayerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShootTheMessengerServer).PlayerStream(&shootTheMessengerPlayerStreamServer{stream})
}

type ShootTheMessenger_PlayerStreamServer interface {
	Send(*PlayerFrame) error
	Recv() (*PlayerFrame, error)
	grpc.ServerStream
}

type shootTheMessengerPlayerStreamServer struct {
	grpc.ServerStream
}

func (x *shootTheMessengerPlayerStreamServer) Send(m *PlayerFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shootTheMessengerPlayerStreamServer) Recv() (*PlayerFrame, error) {
	m := new(PlayerFrame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ShootTheMessenger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stm.ShootTheMessenger",
	HandlerType: (*ShootTheMessengerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginGame",
			Handler:    _ShootTheMessenger_BeginGame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerStream",
			Handler:       _ShootTheMessenger_PlayerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stm/shoot_the_messenger.proto",
}
