project '../TriviaCast.xcodeproj/'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TriviaCast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TriviaCast
  pod 'SnapKit'

  target 'TriviaCastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TriviaCastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
